dependencies:
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: ninjabelt-ng
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.28
- name: ninjabelt-rs
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.20
